# Error Handling in Go

In Go, there is no exception, the unexpected scenario is covered by error and panic.

["Errors are values"](https://go.dev/blog/errors-are-values), most of the time, we will cope with errors as if it's a special value, we can perform a nil check to determine if there is error, and we can also use `errors.Is` and `errors.As` from [1.13](https://go.dev/blog/go1.13-errors) to perform type checking, this is somehow similar to the exception handling in some other languages.

Compared to the normal errors, `panic` is more like a real exception. When the panic statement is executed, the normal flow of the current process will halt and the execution will jump directly into the deferred part where the `recover` statement usually resides in. When a panic is captured from `recover`, it receives the value raised from the panic statement, "catch" it and avoid the process from crashing.
